### ISSUE TITLE
Regarding naming standard (camelCase vs under_score)

### ISSUE THREAD

**Issue by ErikBjare** [johan-bjareholt/zentwm#3]
Google uses underscores in their C++ styleguide (but camelCase for things like classes, types and enums). I'd consider following it as it's generally good practice.
https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Naming

---

Python has also moved away from using camelCase to underscores.

> Function names should be lowercase, with words separated by underscores as necessary to improve readability. mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.

https://www.python.org/dev/peps/pep-0008/#function-names

**Comment by johan-bjareholt** [comment]
Thanks, that insight was just what i needed.

Have always and always will write classes and such in CamelCase, but have always had a hard time deciding to name my functions with CamelCase or with underscores. This makes it easier to distinguish so i guess that it makes sense.

Renamed everything in commit 8c2fd95, closing
